<?php
/**
 * Tasks to run during uninstallation of this plugin.
 *
 * @package wp-webdav-media-library
 */

// prevent direct access.
defined( 'ABSPATH' ) || exit;

// if uninstall.php is not called by WordPress, die.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	die;
}

use KiSa\WebDavMediaLibrary\Plugin\Uninstall;

// do nothing if PHP-version is not 8.1 or newer.
if ( PHP_VERSION_ID < 80100 ) { // @phpstan-ignore if.alwaysFalse,smaller.alwaysFalse
	return;
}

// set the version.
const WWML_PLUGIN_VERSION = '@@VersionNumber@@';

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// run the uninstaller-methods.
Uninstall::get_instance()->run();

