<?php
/**
 * Plugin Name:       WP WebDav Media Library
 * Description:       Independent fork for using WebDav in WordPress Media Library.
 * Requires at least: 6.2
 * Requires PHP:      8.1
 * Requires Plugins:  external-files-in-media-library
 * Version:           1.0.0
 * Author:            KiSa
 * Author URI:        https://github.com/kornalexandr2
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       wp-webdav-media-library
 *
 * @package wp-webdav-media-library
 */

// prevent direct access.
defined( 'ABSPATH' ) || exit;

// do nothing if PHP-version is not 8.1 or newer.
if ( PHP_VERSION_ID < 80100 ) { // @phpstan-ignore if.alwaysFalse,smaller.alwaysFalse
	return;
}

use KiSa\WebDavMediaLibrary\Plugin\Init;

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// bail if "External files in Media Library" is not active.
if ( ! Init::get_instance()->is_parent_plugin_active() ) {
	return;
}

// get plugin-path.
const WWML_PLUGIN = __FILE__;

// set the version.
const WWML_PLUGIN_VERSION = '1.0.0';

// initialize plugin.
Init::get_instance()->init();

